Controllers/AdminController.cs
using Ecommerce.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Ecommerce.Controllers
{

    public class AdminController : Controller
    {
        DoAnEntities database = new DoAnEntities();
        // GET: Admin
        public ActionResult Index()
        {
            if (Session["TenAD"] == null) return RedirectToAction("Error", "Users");
            var products = database.Products;

            return View(products.ToList());

        }

        // xu ly phan user
        public ActionResult qlUser()
        {
            var users = database.Customers;
            return View(users);
        }
        [HttpPost]
        public ActionResult DeleteUser(int id)
        {
            Customer cus = database.Customers.Where(p => p.IDCus == id).FirstOrDefault();
            if (cus != null)
            {
                database.Customers.Remove(cus);
                database.SaveChanges();

            }

            return Json(new { redirectTo = Url.Action("qlUser") });

        }

        // end useer



        [HttpGet]
        public ActionResult Create()
        {
            if (Session["TenAD"] == null) return RedirectToAction("Error", "Users");
            ViewBag.Category = new SelectList(database.Categories, "IDCate", "NameCate");
            return View();

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,NamePro,DecriptionPro,Category,Price,ImagePro")] Product product, HttpPostedFileBase ImagePro)
        {
            if (ModelState.IsValid)
            {
                if (ImagePro != null)
                {
                    var fileName = Path.GetFileName(ImagePro.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/images"), fileName);
                    product.ImagePro = fileName;
                    ImagePro.SaveAs(path);
                }
                database.Products.Add(product);
                database.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Category = new SelectList(database.Categories, "IDCate", "NameCate", product.Category);
            return View(product);
        }


        // GET: Products/Delete/5
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (Session["TenAD"] == null) return RedirectToAction("Error", "Users");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = database.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = database.Products.Find(id);
            database.Products.Remove(product);
            database.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteProducts(int id)
        {
            Product pro = database.Products.Where(p => p.ProductID == id).FirstOrDefault();
            if (pro != null)
            {
                database.Products.Remove(pro);
                database.SaveChanges();
            }

            return Json(new { redirectTo = Url.Action("Index") });
        }
        public ActionResult qlOrder()
        {
            List<OrderDetail>OrderList= database.OrderDetails.ToList();
            List<OrderDetailModel> orderDetailModels = OrderList.Select(
                x => new OrderDetailModel
                {
                    IdOrd =x.IDOrder,
                    IDPro=x.IDProduct,
                    NamePro=x.Product.NamePro,
                    NameCusOrd=x.OrderPro.Customer.NameCus,
                    AddressOrd=x.OrderPro.AddressDeliverry,
                    QuanityOrd=x.Quantity,
                    PriceOrd=x.UnitPrice,
                    DateOrd=x.OrderPro.DateOrder
                }

                ).ToList();
            return View(orderDetailModels);
        }



    }
}

Controllers/IntroduceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ecommerce.Controllers
{
    public class IntroduceController : Controller
    {
        // GET: Introduce
        public ActionResult IndexIntro()
        {
            return View();
        }
    }
}

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ecommerce.Models;

namespace Ecommerce.Controllers
{
    public class ProductController : Controller
    {
        Random random = new Random();
        DoAnEntities database = new DoAnEntities();

        // GET: Product
        public ActionResult Index()
        {
            return View();

        }

        public ActionResult PageCF()
        {
            var productCF = database.Products.Where(p => p.Category == "01");
            return View(productCF);
        }

        public ActionResult PageTra()
        {
            var productTra = database.Products.Where(p => p.Category == "02");
            return View(productTra);
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = database.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        public ActionResult Qcsanpham()
        {
            var sanpham = database.Products.ToList();
            var sanphamRandom = sanpham.OrderBy(x => random.Next()).Take(7).ToList();
            return PartialView(sanphamRandom);
        }

        public ActionResult Menu(string Searching)
        {
            if (Searching != null)
            {
                Session["search"] = Searching;
            }
            return View(database.Products.Where(x => x.NamePro.Contains(Searching) || Searching == null).ToList());

        }


    }
}

Views/Shared/_Layout-admin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <script src="~/Scripts/script.js"></script>
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <!-- Toastr -->
</head>
<style>
    body {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        overflow-x: hidden;
    }
    /*nav*/
    .nav-top {
        position: relative;
        background-color: rgba(225,225,225,0.4);
        top: 0;
        position: fixed;
        width: 100%;
        z-index: 5;
        border-bottom: 0.5px solid #ccc;
    }

    .nav-ul {
        margin: 0;
        display: flex;
        justify-content: center;
        padding-bottom: 19px;
    }

        .nav-ul li {
            padding: 19px 16px;
            list-style: none;
            line-height: 14px;
            font-size: 14px;
            height: 35px;
        }

            .nav-ul li a {
                text-decoration: none;
                color: black;
                font-size: 18px;
                cursor: pointer;
                transition: all ease-in-out 0.5s;
            }

                .nav-ul li a:hover {
                    color: #ea8025;
                }

    .trangchu {
        text-decoration: none;
        color: black;
    }
    /*content*/
    .content {
        margin-top: 74px;
    }
    /*btn cart*/
    .cart {
        position: absolute;
        right: 6%;
    }

        .cart i {
            transition: all ease-in-out 0.5s;
            cursor: pointer;
        }

            .cart i:hover {
                color: #ea8025;
            }
    /*footer*/
    .footer {
        width: 100%;
        height: 500px;
        background-color: #000000D9;
        padding: 25px 0;
    }

        .footer .col {
            font-size: 14px;
            color: #fff;
            font-weight: 600;
            margin-bottom: 16px;
            margin-top: 0;
        }

    .img-logo {
        position: absolute;
        margin-top: -69px;
        height: 159px;
        left: 20px;
    }

    .footer_title {
        font-size: 14px;
        margin-bottom: 16px;
    }

    .footer_link {
        text-align: left;
    }

        .footer_link li {
            list-style: none;
            font-size: 12px;
            margin-bottom: 8px;
        }
</style>
<body>

    <div class="nav-top">
        <ul class="nav-ul">
            <li>
                <a href="/" class="logo">
                    <img class="img-logo" src="~/Images/Logo2.png" alt="#" />
                </a>
            </li>
            <li><a href="@Url.Action("Index","Admin")">Quản lý sản phẩm</a></li>
            <li><a href="@Url.Action("qlUser","Admin")">Quản lý người dùng</a></li>
            <li><a href="@Url.Action("qlOrder","Admin")">Quản lý đơn hàng</a></li>
           
            <li class="button" style="right:0; position:absolute">
                    <a class="button" style="right:0; position:absolute; margin-left:5px" href="@Url.Action("Logout","Users")">

                        <i class="fas fa-sign-out-alt"></i>
                    </a>
            </li>


        </ul>

    </div>

    <div>
        <div class="content">
            @RenderBody()
        </div>
    </div>

    <!-- Footer -->
    @Html.Action("footer", "Home")
    <!-- Footer -->


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/Scripts/toastr.js"></script>
</body>

</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <script src="~/Scripts/script.js"></script>
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <!-- Toastr -->
</head>
<style>
    body {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        overflow-x: hidden;
    }
    /*nav*/
    .nav-top {
        position: relative;
        background-color: rgba(225,225,225,0.4);
        top: 0;
        position: fixed;
        width: 100%;
        z-index: 5;
        border-bottom: 0.5px solid #ccc;
    }

    .nav-ul {
        margin: 0;
        display: flex;
        justify-content: center;
        padding-bottom: 19px;
    }

        .nav-ul li {
            padding: 19px 16px;
            list-style: none;
            line-height: 14px;
            font-size: 14px;
            height: 35px;
        }

            .nav-ul li a {
                text-decoration: none;
                color: black;
                font-size: 18px;
                cursor: pointer;
                transition: all ease-in-out 0.5s;
            }

                .nav-ul li a:hover {
                    color: #ea8025;
                }

    .trangchu {
        text-decoration: none;
        color: black;
    }
    /*content*/
    .content {
        margin-top: 74px;
    }
    /*btn cart*/
    .cart{
        position:absolute;
        right:6%;
    }
    .cart i{
        transition:all ease-in-out 0.5s;
        cursor:pointer;
    }
        .cart i:hover {
            color: #ea8025;
        }
    /*footer*/
    .footer {
        width: 100%;
        height: 500px;
        background-color: #000000D9;
        padding: 25px 0;
    }

        .footer .col {
            font-size: 14px;
            color: #fff;
            font-weight: 600;
            margin-bottom: 16px;
            margin-top: 0;
        }

    .img-logo {
        position: absolute;
        margin-top: -69px;
        height: 159px;
        left: 20px;
    }

    .footer_title {
        font-size: 14px;
        margin-bottom: 16px;
    }

    .footer_link {
        text-align: left;
    }

        .footer_link li {
            list-style: none;
            font-size: 12px;
            margin-bottom: 8px;
        }
</style>
<body>

    <div class="nav-top">
        <ul class="nav-ul">
            <li>
                <a href="/" class="logo">
                    <img class="img-logo" src="~/Images/Logo2.png"  height="10%" alt="#" />
                </a>
            </li>
            <li><a href="@Url.Action("PageCF","Product")">Cà phê</a></li>
            <li><a href="@Url.Action("PageTra","Product")">Trà</a></li>
            <li><a href="@Url.Action("Menu","Product")">Cửa Hàng</a></li>
            <li><a href="@Url.Action("IndexIntro","Introduce")">Giới Thiệu</a></li>
            <li class="cart">
                @Html.Action("CartPartial", "Cart")
            </li>
            <li class="button" style="right:0; position:absolute">
                @if (Session["Ten"] == null)
                {
                    <a href="@Url.Action("Login", "Users")">Đăng nhập</a>

                }
                else
                {
                    <a title="Thông tin khách hàng" href="@Url.Action("ViewProfile","Users")" style="margin-right:1em;">@Session["Ten"]</a>

                    <a class="button" style="right:0; position:absolute; margin-left:5px" href="@Url.Action("Logout","Users")">

                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                }
            </li>



        </ul>

    </div>

    <div>
        <div class="content">
            @RenderBody()
        </div>
    </div>

    <!-- Footer -->
    @Html.Action("footer", "Home")
    <!-- Footer -->
   
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/Scripts/toastr.js"></script>
</body>

</html>

Views/Shared/_Loading.cshtml
<link href="~/Content/Loading.css" rel="stylesheet" />
<div class="preloader">
    <svg class="cart" role="img" aria-label="Shopping cart line animation" viewBox="0 0 128 128" width="128px" height="128px" xmlns="http://www.w3.org/2000/svg">
        <g fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="8">
            <g class="cart__track" stroke="hsla(0,10%,10%,0.1)">
                <polyline points="4,4 21,4 26,22 124,22 112,64 35,64 39,80 106,80" />
                <circle cx="43" cy="111" r="13" />
                <circle cx="102" cy="111" r="13" />
            </g>
            <g class="cart__lines" stroke="currentColor">
                <polyline class="cart__top" points="4,4 21,4 26,22 124,22 112,64 35,64 39,80 106,80" stroke-dasharray="338 338" stroke-dashoffset="-338" />
                <g class="cart__wheel1" transform="rotate(-90,43,111)">
                    <circle class="cart__wheel-stroke" cx="43" cy="111" r="13" stroke-dasharray="81.68 81.68" stroke-dashoffset="81.68" />
                </g>
                <g class="cart__wheel2" transform="rotate(90,102,111)">
                    <circle class="cart__wheel-stroke" cx="102" cy="111" r="13" stroke-dasharray="81.68 81.68" stroke-dashoffset="81.68" />
                </g>
            </g>
        </g>
    </svg>
    <div class="preloader__text">
        <p class="preloader__msg">Bringing you the goods…</p>
        <p class="preloader__msg preloader__msg--last">This is taking long. Something’s wrong.</p>
    </div>
</div>